Setup security checks (#3)
* Setup security checks

* workflow update. Secret scanner

* Project updates

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* Delete docker/.env

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,6 +1,10 @@
 name: Test CI
 
-on: [ push, pull_request ]
+on:
+  pull_request:
+    branches:
+      - main
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -41,21 +45,21 @@ jobs:
         run: |
           mvn -e -fae clean test
 
-      - name: Generate JaCoCo Report
-        run: mvn jacoco:report
-
-      - name: Run Checkstyle
-        run: mvn checkstyle:check
-
-      - name: Print surefire reports on failure
-        if: failure()
-        run: |
-          echo "=== surefire reports ==="
-          ls -la target/surefire-reports || true
-          for f in target/surefire-reports/*.txt; do
-            echo "----- $f -----"
-            sed -n '1,200p' "$f" || true
-          done
+#      - name: Generate JaCoCo Report
+#        run: mvn jacoco:report
+#
+#      - name: Run Checkstyle
+#        run: mvn checkstyle:check
+#
+#      - name: Print surefire reports on failure
+#        if: failure()
+#        run: |
+#          echo "=== surefire reports ==="
+#          ls -la target/surefire-reports || true
+#          for f in target/surefire-reports/*.txt; do
+#            echo "----- $f -----"
+#            sed -n '1,200p' "$f" || true
+#          done
 
 #      - name: Build test report
 #        uses: simple-elf/allure-report-action@v1.7
